In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5]) 
N=5 
matrix = np.vander(x,N,increasing=False)
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [29]:
def move_avg(mylist, N):
    num, moving = [0], []
    for i, x in enumerate(mylist, 1):
        num.append(num[i-1] + x)
        if i>=N:
            moving_avg = round(((num[i] - num[i-N])/N),2) 
            moving.append(moving_avg)
    print("Moving average values: ", moving)
    print("Length of the list n-k+1: ", len(moving))

In [30]:
mylist = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
n = 4

move_avg(mylist,n)

Moving average values:  [25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]
Length of the list n-k+1:  7


In [31]:
mylist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n = 3

move_avg(mylist,n)

Moving average values:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
Length of the list n-k+1:  11
